### ISSUE TITLE
Cannot import name 'DeviceInfo'

### ISSUE THREAD

**Issue by janbru** [physje/waterinfo#1]
Home Assistant 2022.10.5 
Frontend 20221010.0 - latest 

```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 17:21:06 (1 occurrences)
Last logged: 17:21:06

Unable to prepare setup for platform waterinfo.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

**Comment by physje** [comment]
I can reproduce the error with your version of Home Assistant. Don't know what is causing the problem.
In my development environment and my production environment (both recent HA-versions) the error is not there.

With older versions of HA their is indeed an error. With newer versions the error is gone and the component works as intended.

Tried several versions, in 2023.08 the error is there, in 2023.09 it works fine. So the difference is somewhere between those 2 software versions. Have to narrow down with version 'breaks' the component and look into release notes to figure out what's going on.

Solution for the short term : update your setup to HA 2023.9 or newer

**Comment by physje** [comment]
In `2023.9` the location of DeviceInfo is changed (See [Changelog Home Assistant Core 2023.9](https://www.home-assistant.io/changelogs/core-2023.9) and especially '[Move DeviceInfo from entity to device registry](https://github.com/home-assistant/core/pull/98149)'.)

So older HA-versions (before 2023.9) will not be supported in this component.

**Comment by janbru** [comment]
Upgrading did the trick, thanks!
