### ISSUE TITLE
Low and High tide for a specific location

### ISSUE THREAD

**Issue by Dynamix72** [physje/waterinfo#2]
Is it possible to add some extra sensors:
low tide
high tide
low tide next
high tide next

based on the data table from https://getij.rws.nl/ (astronomical tide) ?

Maybe this code will help...
https://gist.github.com/baidarka/3dfa106867b2782cdeb68c517ff92a78

**Comment by physje** [comment]
Based on the URL you gave and the code of baidarka I don't think is possible.
The RWS API only has calls on ` https://waterwebservices.rijkswaterstaat.nl/`.

If you find a way to do it, feel free to do a pull-request.

**Comment by Mariusthvdb** [comment]
woulkn't this be the following info:
https://waterinfo.rws.nl/#/publiek/waterhoogte/Oosterschelde-4-%28b%29%28OS4b%29/details?parameters=Waterhoogte___20Oppervlaktewater___20t.o.v.___20Normaal___20Amsterdams___20Peil___20in___20cm

might not be the official Tides, but Water height fluctuates according to the tides?
