### ISSUE TITLE
[possible bug] Old data for Krimpen a/d IJssel

### ISSUE THREAD

**Issue by DemianTinkiel** [physje/waterinfo#4]
Firstly thanks for the integration, it's really awesome and I didn't know something like it existed!

When comparing the integration with the site I see that I get -19cm water height vs 90cm in the website (small difference 🤣)
Looking at the attributes in the integration it says Last data September 7, 1993 at 00:50:00
So maybe that is the reason 

location-code : KRIMPADIJSL
Measure-code: WATHTBRKD

![Screenshot_20240927_051627_Chrome](https://github.com/user-attachments/assets/eaa827a4-0336-48a3-bb7a-0a61cb740e48)
![Screenshot_20240927_051825_Chrome](https://github.com/user-attachments/assets/c558f805-f985-4d25-b72c-00199de2e475)

**Comment by physje** [comment]
I think you're using the wrong measurement-code / location-code.

The measurement-code `WATHTBRKD` means "Waterhoogte _berekend_ Oppervlaktewater t.o.v. Normaal Amsterdams Peil in cm", based on the lower graph I think you're looking for measurement-code `WATHTE` (Waterhoogte Oppervlaktewater t.o.v. Normaal Amsterdams Peil in cm).

So I think this will give the expected results :
location-code : KRIY
Measure-code: WATHTE

(don't ask me why the location-code is different, that's something RWS does)

**Comment by physje** [comment]
In your first screenshot is another combination of measurement-code and location-code visible than you mention in the text.

You're mentioning
location-code : KRIMPADIJSL
Measurement -code: WATHTBRKD

Visible is
location-code : KRIMPADIJSL
Measurement -code: WATHTE

This combination does not exist, so will give random results.
